# Generated by Django 4.0.4 on 2022-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='description', verbose_name='Описание функции')),
            ],
            options={
                'verbose_name': 'Описание функций',
            },
        ),
    ]
