# Generated by Django 4.0.4 on 2022-05-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botfunctions',
            name='name',
            field=models.TextField(db_column='name', default=None, verbose_name='Название функции'),
            preserve_default=False,
        ),
    ]
