# Generated by Django 4.0.4 on 2022-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_botfunctions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_msg', models.TextField(db_column='user_msg', verbose_name='Сообщение от пользователя')),
                ('reply_msg', models.TextField(db_column='reply_msg', verbose_name='Ответ')),
                ('positive', models.BooleanField(db_column='positive', default=True, verbose_name='Поизитивная или негативная фраза(True/False)')),
                ('score', models.IntegerField(db_column='score', verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'Фразы',
            },
        ),
    ]
