# Generated by Django 4.0.4 on 2022-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dialogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(db_column='urls', verbose_name='Ссылка на картинку')),
                ('tags', models.TextField(db_column='tags', verbose_name='тэг(животные,пейзажи,смешнявка,пикчи,мои фоточки)')),
                ('coment', models.BooleanField(db_column='coment', null=True, verbose_name='коментарий к картинке(не обязателен)')),
            ],
            options={
                'verbose_name': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(db_column='urls', verbose_name='Ссылка на видео')),
                ('tags', models.TextField(db_column='tags', verbose_name='тэг(для чила,животные,Смешные видео)')),
                ('coment', models.BooleanField(db_column='coment', null=True, verbose_name='коментарий к видео(не обязателен)')),
            ],
            options={
                'verbose_name': 'Видео',
            },
        ),
    ]
