# Generated by Django 4.0.4 on 2022-05-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pictures_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name': 'Картинки'},
        ),
    ]
