# Generated by Django 4.0.4 on 2022-05-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pictures_coment_alter_videos_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='coment',
            field=models.TextField(blank=True, db_column='coment', null=True, verbose_name='коментарий к картинке(не обязателен)'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='coment',
            field=models.TextField(blank=True, db_column='coment', null=True, verbose_name='коментарий к видео(не обязателен)'),
        ),
    ]
