# Generated by Django 4.0.4 on 2022-05-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pictures_coment_alter_videos_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='url',
            field=models.TextField(db_column='url', verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='url',
            field=models.TextField(db_column='url', verbose_name='Ссылка на видео'),
        ),
    ]
