# Generated by Django 4.0.4 on 2022-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pictures_url_alter_videos_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField(db_column='urls', verbose_name='Ссылка на сайт с аниме(Aniu)')),
                ('name', models.TextField(db_column='name', verbose_name='Жанр аниме')),
            ],
            options={
                'verbose_name': 'Аниме',
            },
        ),
    ]
